### ISSUE TITLE
使用建议

### ISSUE THREAD

**Issue by kofzhanganguo** [xi-mad/my_video#1]
![image](https://user-images.githubusercontent.com/32073931/229416797-c45874ce-4a9f-4176-987e-f0a28054c3dd.png)
首先这个CMD窗口，应该创建个EXE的程序，隐藏这个CMD窗口，然后放置在系统托盘下，右键可以设置点功能，比如退出，重启啥的，而不是总是让这个窗口在任务栏底部显示，当我关闭这个CMD窗口的时候，软件也就关闭了，这样很麻烦。
![image](https://user-images.githubusercontent.com/32073931/229417009-6fbf6975-b0b9-437f-a8b3-ce2bf33d33f1.png)
![image](https://user-images.githubusercontent.com/32073931/229417028-f1baba1d-fd42-4b8c-9929-3df2d193d109.png)
类似EMBY这种的托盘管理。
第二个问题，就是WEBUI中，可以设置软件的具体参数，而不是去修改config配置文件，因为在WEBUI中可以直观的设置软件具体的参数，这样更加明确。
![image](https://user-images.githubusercontent.com/32073931/229417315-498042d8-b8c5-456d-9420-e530c3119883.png)
比如NASTOOL这种，设置上更加方便。
![image](https://user-images.githubusercontent.com/32073931/229417404-f051b989-ce86-4042-a133-79c061c6efb0.png)
还有一个问题，就是修改具体软件的端口参数，比如软件默认使用的端口号是8080，那么8080端口其他软件占用的情况下，那么只能二选一，修改其他软件的端口号，或者是修改你这款软件的端口号，起码软件要给个可以修改端口参数的设置。
![image](https://user-images.githubusercontent.com/32073931/229417709-a98b0264-1047-4baf-af52-53c194306e3c.png)
还有首次使用本软件的时候，应该给个默认的登录帐号和密码，首次打开软件的时候，显示默认登录名，默认密码，然后登录进去后，让用户自行修改用户名和密码，这样比较方便首次使用的用户。

**Comment by xi-mad** [comment]
目前已经发布支持配置端口号的版本，其余问题会持续跟进。如果有好的技术方案提供，欢迎交流。

**Comment by xi-mad** [comment]
已将程序默认移动到托盘栏，欢迎体验

**Comment by kofzhanganguo** [comment]
作者同志，你好，希望你的软件能完美支持NFO，做成中国区的EMBY，有时间用你的软件，添加我几万部片子，看看软件卡不卡，国产的影视管理软件，极影派，易影视，Jvedio，ALEX等等，都不太理想，几千部片子就卡飞了，起码我用EMBY，PLEX，jellyfin，流媒体服务器软件，几万部片子我测试过，是没任何问题的，Windows本地的客户端软件，比如KODI，emdb，tinyMediaManager，Filmotech，Ember Media Manager等等这些，都不会卡，几万部片子也没事儿。
![image](https://user-images.githubusercontent.com/32073931/232541247-011db75a-fc96-42a5-a095-744fc9fb8c1c.png)
影片数量过万了。
![image](https://user-images.githubusercontent.com/32073931/232541535-df2f1394-cdf8-4416-9517-7e660e495c59.png)
![image](https://user-images.githubusercontent.com/32073931/232541592-a4b4e7f2-b4bb-4918-be0a-b52fb28a57be.png)
这是我能找到的所有关于管理影视的软件了，顺便做了全部汉化。

**Comment by xi-mad** [comment]
哈哈 欢迎体验，顺便帮忙测试。有问题及时沟通

**Comment by kofzhanganguo** [comment]
问题出现了，全新下载，运行程序，没任何反应
![image](https://user-images.githubusercontent.com/32073931/232542834-6439a40b-e1d5-4ce9-8042-607a88873c21.png)
解压缩后的文件夹。
![image](https://user-images.githubusercontent.com/32073931/232542897-ec6b2c71-f52a-42b0-9211-6a843049b68d.png)
然后释放出配置文件夹等目录
然后我该如何打开？没任何反应

**Comment by xi-mad** [comment]
右下角托盘栏应该是有图标的，看一下

**Comment by kofzhanganguo** [comment]
![image](https://user-images.githubusercontent.com/32073931/232543410-d2eb735c-ab13-4e18-b01b-eae03c816e8e.png)
看不到

**Comment by kofzhanganguo** [comment]
应该把所有运行的东西，都放在一起打包，而不是让运行程序双击释放出来，释放出来的是文件夹全部是空的。

**Comment by xi-mad** [comment]
抱歉，我的更新方式是基于上一个版本的。有历史版本的用户，担心覆盖他们的配置文件，所以默认是类似增量更新的方式。我更新了新的程序包，可以在尝试一下，我本地是没问题的。对你带来的困扰感到抱歉
https://github.com/xi-mad/my_video/releases/download/v1.3.2/my_video.rar

**Comment by kofzhanganguo** [comment]
你可以做个全新的包，适配第一次使用用户，不然新用户下载你的最新程序后，打开一脸懵逼，然后在去下载你首发的第一个版本，然后两边替换，这样啥人能知道咋用啊，还有首次运行程序后，应该首先打开浏览器网页，让用户自己直观的知道程序在运行了，而不是去浏览器打IP地址，进去网页，还有就是端口号，最好是保持和其他的软件没有冲突，最好是一些稀奇古怪的端口号，不然容易造成浏览器网页打不开，比如群晖那种5000的默认端口号啥的。

**Comment by kofzhanganguo** [comment]
![image](https://user-images.githubusercontent.com/32073931/232546555-f53ce14d-16a7-4b76-b7b3-f65f3132d7b3.png)
右键托盘，能不能选择一个就是打开网页页面，也就是打开媒体库。

**Comment by kofzhanganguo** [comment]
首先我要搞懂软件咋用。。。。。。
我片子几万部，压力测试都是小事儿，还有就是，不知道能不能管理剧集，貌似都是单独的视频文件
![image](https://user-images.githubusercontent.com/32073931/232548803-3e49a1da-e2c2-4709-b1e4-2c6d2162fad2.png)
我想这种应该很容易做到吧。
![image](https://user-images.githubusercontent.com/32073931/232548990-7b42cd47-7107-4a54-8edc-2d73194a1a75.png)
这种剧集的，能做到吗？

**Comment by xi-mad** [comment]
我想保持程序的简单性，所以目前的入口都在路径扫描。
对于剧集管理，目前有一个肤浅的想法，可以新增一个剧集管理的导航栏，允许用户创建剧集并引用对象中的剧集。
但这样的工作量仍然会很高，目前没有想到更自动化的方式。

**Comment by kofzhanganguo** [comment]
我就是添加个路径扫描，然后内存过4G以上，硬盘220多MB的读取。

**Comment by xi-mad** [comment]
因为要读取文件的前50MB计算hash值用于去重，所以会有很大的硬盘读写，或许这个值应该改小一些。 我还没有遇到内存使用很高的情况。
 太晚了，明天再搞吧 - -

**Comment by kofzhanganguo** [comment]
文件去重，其实本身视频文件也很少有MD5哈希值校验去重的，如果是AV的话，都是番号去重，正规片都是数据库的ID编号去重，那些所谓的小视频，去重复大多数也没啥意义，如果想单独文件去重复，有专业的哈希值校验软件去重复，视频管理软件没有任何一款是使用哈希值去重复的。

**Comment by kofzhanganguo** [comment]
![image](https://user-images.githubusercontent.com/32073931/232553865-459eabdc-a905-4ea8-97ab-d7a424bc97f7.png)
以正规片为例，都是数据库编号去重复
![image](https://user-images.githubusercontent.com/32073931/232554171-f49ec493-011c-4681-bea9-376765189ac8.png)
日本动作片都是番号去重

**Comment by xi-mad** [comment]
请不要讨论av，谢谢。 计算hash值只取了文件的前50mb计算，并没有完全读一遍。 对于去重可能还需要进一步考虑

**Comment by xi-mad** [comment]
新版移除了hash计算，经测试没有再大量占用磁盘和内存情况
https://github.com/xi-mad/my_video/releases/download/v1.3.3/my_video_full.rar
