### ISSUE TITLE
exit status 0xc0000135

### ISSUE THREAD

**Issue by ParanoiAMD** [xi-mad/my_video#10]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：1.3.7
- 电脑系统：Win11 21H2

### 描述：

扫描文件提示：

find file: F:\xxx\xxx,mp4 
path: F:\xxx\xxx,mp4,error: exit status 0xc0000135

请问这是什么情况？

btw:依旧没有log文件生成

**Comment by xi-mad** [comment]
看起来是因为.net framework的问题，请尝试以下方案：
https://www.yundongfang.com/Yun165006.html

日志应该是有的。

**Comment by xi-mad** [comment]
第一次打开是没有日志的，第二次打开应该就有了

**Comment by ParanoiAMD** [comment]
2023/04/27 22:06:21 D:/projects/my_video/backend/object/models.go:327
[0.000ms] [rows:1] SELECT count(*) FROM `object` WHERE path = "F:\Jable-E\123\abc.mp4"
2023/04/27 22:06:21 exec cmd: F:/mtn-200808a/mtn.exe [-P -w 2048 -c 4 -r 4 -f C:/Windows/Fonts/STSONG.TTF -o _1682604381314040000.jpg -O ./temp F:\Jable-E\123\abc.mp4], err: exit status 0xc0000135
2023/04/27 22:06:21 mtn error: exit status 0xc0000135 

这是log里的提示

**Comment by xi-mad** [comment]
查了一下，应该是.net framework的问题，目前在win10，win11 22H2没有遇到这样的问题。如下等网站提供了解决方案，希望对你有帮助：
https://www.makeuseof.com/fix-windows-app-error-0xc0000135-on-windows/
https://answers.microsoft.com/en-us/windows/forum/all/0xc0000135-error-when-opening-most-applications/7db10be2-66fb-4e5d-b553-8fa524bb2124
https://www.youtube.com/watch?v=iWcoUJZyPO4
