### ISSUE TITLE
电影文件名因为长短不一，会造成列表参差不齐

### ISSUE THREAD

**Issue by euzenlee** [xi-mad/my_video#11]
电影文件名因为长短不一，会造成列表参差不齐，强迫症受不了。这软件一个受众就是收纳爱好者，要考虑一下他们的感受啊。

另外扫描进来的对象不能删除的吗？

**Comment by xi-mad** [comment]
扫描的对象在上方切换为管理模式可以删除。
列表参差不齐指的是什么，视频本身有竖向的。

**Comment by euzenlee** [comment]
列表对不齐，指的是第一行的四张图是齐平的，但因为有的文件名过长，换行后占两三行，有的只占一行，所以每张“资料卡片”的长度不一。到第二、三、四列的图片，就不是在一水平线上了。

**Comment by xi-mad** [comment]
主要考虑的是有的竖向的视频，才使用这种类似照片墙的方式。
会设计一种对齐的方案的

**Comment by xi-mad** [comment]
https://github.com/xi-mad/my_video/releases/tag/v1.3.8
已支持通过配置对象高度 实现对齐的效果
