### ISSUE TITLE
大佬能不能增加文件名搜索功能这样初步管理的时候方便勾选

### ISSUE THREAD

**Issue by Uiisland** [xi-mad/my_video#12]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

1.大佬能不能增加文件名搜索功能这样初步管理的时候方便勾选
2.添加一个在对象管理里面管理模式下 多选的时候批量添加标签

### 反馈/建议

![image](https://github.com/xi-mad/my_video/assets/93713004/af2c058f-7264-4f43-b741-1ebe9fd7da7b)

**Comment by xi-mad** [comment]
问题一，在路径那里包含了文件名，可以直接搜索。
问题二，批量打标签会考虑怎样实现比较方便，后续会支持。
