### ISSUE TITLE
我也做了一个类似的, 可以聊聊.

### ISSUE THREAD

**Issue by mingyuantech** [xi-mad/my_video#4]
![image](https://user-images.githubusercontent.com/11971917/233805908-7e67ea20-b8ba-4916-bc1c-e693b76a76c6.png)
你看看我这个咋样

**Comment by edgar88** [comment]
有下载链接或github链接吗？

**Comment by xi-mad** [comment]
开源吗，可以体验一下。对了 请不要放这么暴露的图片
