### ISSUE TITLE
朋友  双击打开 没反应

### ISSUE THREAD

**Issue by dnwyl2023** [xi-mad/my_video#6]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：最新版本的软件 第一次打开弹出成功  后来再也没成功过
- 电脑系统：WIN10
- 提出的建议：看到EXE格式的文件就紧张  还有软件有海报墙么 点一下还会生成新的那种

### 描述：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

详细说明前因后果、操作步骤。

### 日志截图：

> **请勿上传任何暴力、色情、恐怖的信息或图片！**

**Comment by xi-mad** [comment]
看右下角托盘栏，没有的话看下log文件夹的日志，贴过来

**Comment by dnwyl2023** [comment]
右下角没有东西 我确认过好几次 因为 第一次有

**Comment by xi-mad** [comment]
那麻烦贴一下log文件夹的日志

**Comment by VWRYNNN** [comment]
请问出现这种情况怎么解决
find file: G:\电影\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字.mp4
path: G:\电影\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字.mp4, error: open D:\functionalapp\my video\temp\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字_1682250611349396300.jpg: The system cannot find the file specified.
扫描完成。

**Comment by xi-mad** [comment]
> 请问出现这种情况怎么解决 find file: G:\电影\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字.mp4 path: G:\电影\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字.mp4, error: open D:\functionalapp\my video\temp\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字_1682250611349396300.jpg: The system cannot find the file specified. 扫描完成。

看起来是D:\functionalapp\my video\temp\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字_1682250611349396300.jpg 这个文件是损坏的，可以看下temp文件夹下的这个文件是否能正常打开

**Comment by zw900** [comment]
你的mtn.exe可能是写错符号了，默认windows路径复制下来是\，但是config.yaml中应该改成/

**Comment by dnwyl2023** [comment]
> 那麻烦贴一下log文件夹的日志

哥 LOG里面是空的 我没必要耍你  LOG里面是真的  这里可以帖图么

**Comment by dnwyl2023** [comment]
![LOG](https://user-images.githubusercontent.com/125647669/233847924-59fa9cba-6500-4145-bad1-7fd05bc77d7c.png)

**Comment by dnwyl2023** [comment]
现在双击 只会打一圈 然后软件没反应  我关机重启过 删了重解压都没用

**Comment by dnwyl2023** [comment]
> 你的mtn.exe可能是写错符号了，默认windows路径复制下来是\，但是config.yaml中应该改成/

我的天 我试了下 真的能打开了

**Comment by dnwyl2023** [comment]
> 你的mtn.exe可能是写错符号了，默认windows路径复制下来是\，但是config.yaml中应该改成/

赞美英雄 666

**Comment by xi-mad** [comment]
这只是一个正常的交流拍错的过程。解决了就好

**Comment by dnwyl2023** [comment]
> 这只是一个正常的交流拍错的过程。解决了就好

勇士  求照片墙

**Comment by xi-mad** [comment]
> > 这只是一个正常的交流拍错的过程。解决了就好
> 
> 勇士 求照片墙

需要什么功能可以开新的issue提，最好描述详细一些
