### ISSUE TITLE
请问出现这种提示是什么情况

### ISSUE THREAD

**Issue by VWRYNNN** [xi-mad/my_video#7]
find file: G:\电影\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字.mp4
path: G:\电影\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字.mp4, error: open D:\functionalapp\my video\temp\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字_1682250611349396300.jpg: The system cannot find the file specified.
扫描完成。

**Comment by xi-mad** [comment]
看起来是D:\functionalapp\my video\temp\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字_1682250611349396300.jpg 这个文件是损坏的，可以看下temp文件夹下的这个文件是否能正常打开

**Comment by VWRYNNN** [comment]
不是很明白，意思是把视频放到这个文件夹里吗

**Comment by xi-mad** [comment]
> 不是很明白，意思是把视频放到这个文件夹里吗

D:\functionalapp\my video\temp\  看一下这个文件夹里面的这个文件“毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字_1682250611349396300.jpg”是否能打开

**Comment by VWRYNNN** [comment]
文件夹里没有这个文件

**Comment by xi-mad** [comment]
能分享一下这个文件吗，也许我需要测试一下

**Comment by VWRYNNN** [comment]
就是下载的电影，路径扫描其他文件夹也是这样

**Comment by xi-mad** [comment]
暂时没有遇到这样的情况。请问你有修改配置文件吗

**Comment by VWRYNNN** [comment]
thumbnail:
  mtn: "D:/soft/mtn-200808a-win32/mtn.exe" 
  font: "C:/Windows/Fonts/STSONG.TTF"
修改了mtn，改成了实际的文件夹
font没有改

**Comment by VWRYNNN** [comment]
会是mtn-200808a-win32没有生成图片吗

**Comment by xi-mad** [comment]
或许是的，看一下程序目录的log文件夹，把日志贴过来看看

**Comment by VWRYNNN** [comment]
2023/04/23 20:14:30 D:/projects/my_video/backend/object/models.go:303
[0.000ms] [rows:1] SELECT count(*) FROM `object` WHERE path = "G:\电影\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字\毒液：致命守护者.Venom.BD1080P.X264.AAC.中英双字.mp4"
[GIN] 2023/04/23 - 20:14:30 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:14:33 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:14:33 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:14:37 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:14:41 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:14:45 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:14:49 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:14:53 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:14:57 | 200 |       136.5µs |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:01 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:05 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:09 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:13 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:17 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:21 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:25 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:29 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:33 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:37 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:41 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:15:45 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:16:25 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:17:25 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:18:25 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:19:25 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
[GIN] 2023/04/23 - 20:20:25 | 200 |            0s |       127.0.0.1 | GET      "/api/object/log"
2023/04/23 20:21:05 exit status 1

**Comment by VWRYNNN** [comment]
成功了，没有宋体，更改后就可以了

**Comment by xi-mad** [comment]
ok

**Comment by VWRYNNN** [comment]
另外请问，有删除视频的功能吗

**Comment by xi-mad** [comment]
在”对象管理“界面，上方有“管理模式”，可以删除索引的记录，不会删除磁盘上的视频文件。

**Comment by VWRYNNN** [comment]
感谢
