### ISSUE TITLE
设置MTN和PotPlayer路径之后扫描目标文件夹出现“Request failed with status code 500”

### ISSUE THREAD

**Issue by ParanoiAMD** [xi-mad/my_video#9]
> **请勿上传任何暴力、色情、恐怖的信息或图片！**

### 反馈/建议

- 出现问题的版本：最新版
- 电脑系统：**win11**
- 提出的建议：xxx

### 描述：

**设置MTN和PotPlayer路径之后扫描目标文件夹出现“Request failed with status code 500”**

### 日志截图：

**无日志生成**

**Comment by xi-mad** [comment]
看下log文件夹的日志

**Comment by ParanoiAMD** [comment]
> 看下log文件夹的日志

空的，没有log文件

**Comment by xi-mad** [comment]
https://github.com/xi-mad/my_video/releases/tag/v1.3.6

发布了1.3.6版本，当程序异常退出时，会记录日志信息，试下这个。顺便一提，在配置文件中的斜杠要写反斜杠，例如这样：D:/soft/mtn-200808a-win32/mtn.exe

**Comment by ParanoiAMD** [comment]
> https://github.com/xi-mad/my_video/releases/tag/v1.3.6
> 
> 发布了1.3.6版本，当程序异常退出时，会记录日志信息，试下这个。顺便一提，在配置文件中的斜杠要写反斜杠，例如这样：D:/soft/mtn-200808a-win32/mtn.exe

I'll try it later, thx
